### ISSUE TITLE
error-chain doesn't work on stable 1.10!

### ISSUE THREAD

**Issue by brson** [brson/error-chain#12] opened 2016-07-22 20:29 UTC
I thought error-chain worked on stable but it doesn't seem to:

```
brian@ip-10-145-43-250:~/dev/error-chain⟫ cargo test
   Compiling error-chain v0.2.2 (file:///mnt/dev/error-chain)
<error_chain macros>:37:24: 37:27 error: expected expression, found keyword `pub`
<error_chain macros>:37 # [ derive ( Debug ) ] pub struct $ error_name (
                                               ^~~
error: Could not compile `error-chain`.

To learn more, run the command again with --verbose.
```

If I try to test further back on 1.9 the errors are even worse:

```
brian@ip-10-145-43-250:~/dev/error-chain⟫ cargo test
   Compiling gcc v0.3.32
   Compiling cfg-if v0.1.0
   Compiling winapi-build v0.1.1
   Compiling winapi v0.2.8
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `winapi-build`.

To learn more, run the command again with --verbose.
```

**Comment by benaryorg** [comment] 2016-07-26 20:57
I don't know what's happening here, but I am using error-chain on stable Rust and it *seemed* to work flawlessly.

**Comment by benaryorg** [comment] 2016-07-26 21:02
I just checked and error-chain builds (and works) with that:

```text
cargo 0.11.0-nightly (259324c 2016-05-20)
rustc 1.10.0 (cfcb716cf 2016-07-03)
```

**Comment by brson** [comment] 2016-07-26 22:11
Oh, nice. Thanks for testing @benaryorg.

**Comment by benaryorg** [comment] 2016-07-27 02:54
Also, I've retested with version 0.2.2 and still the same result, a seamless build without any error/mistake.

**Comment by birkenfeld** [comment] 2016-08-06 18:34
The problem is with using `error_chain` inside a function, as in the smoke tests.

It is "easily" (once you figure it out) fixed by appending a semicolon. PR incoming.

**Closed** 2016-08-07 02:49 UTC

**Comment by brson** [comment] 2016-08-09 01:33
Thanks @birkenfeld !
